name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1
        with:
          otp-version: "28"
          elixir-version: "1.20"
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
      - run: mix deps.get
      - run: git diff --exit-code -- mix.lock
      - run: mix format --check-formatted
      - run: mix compile --warnings-as-errors
      - run: mix test --warnings-as-errors
      - run: mix docs
      - run: mix hex.audit
